### ISSUE TITLE
allow to set time-out

### ISSUE THREAD

**Issue by wjo1212** [aliyun/aliyun-log-cli#10]
due to network or server side issue, it may time-out in 20 seconds, better to make it configurable.

```shell
/home/travis/virtualenv/python3.3.6/bin/python "/home/travis/build/aliyun/aliyun-log-cli/tests/../aliyunlogcli/cli.py" log create_logstore --project_name="dlq-test-cli-56913" --logstore_name="logstore1" --ttl=2 --shard_count="2"
Status : FAIL 2
{"errorCode": "LogRequestError", "errorMessage": "HTTPConnectionPool(host='dlq-test-cli-56913.[secure]', port=80): Max retries exceeded with url: /logstores (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f149a6e5910>, 'Connection to dlq-test-cli-56913.[secure] timed out. (connect timeout=20)'))", "requestId": ""}
Traceback (most recent call last):
  File "./test_cli.py", line 14, in <module>
    test_main()
  File "./test_cli.py", line 10, in test_main
    run_test(file_path)
  File "/home/travis/build/aliyun/aliyun-log-cli/tests/util.py", line 75, in run_test
    assert return_code == 0, ValueError('cmd return code "{0}" is as expected "0"'.format(return_code))
AssertionError: cmd return code "2" is as expected "0"

```

**Comment by wjo1212** [comment]
the time-out is changed to 60seconds
